### ISSUE TITLE
Misaligned window controls on nonstandard display

### ISSUE THREAD

**Issue by LSeelig** [bmFtZQ/edge-frfox#65] opened 2022-11-04 21:11 UTC
**Description**
On a secondary display (mine has different aspect ratio and scaling factor, the close, maximize, and minimize controls are unaligned).

**Include screenshot / video recording if possible.**
![image](https://user-images.githubusercontent.com/37001137/200075099-4c1ca17f-c315-4f47-b638-940627907c01.png)

**Configuration**
- Firefox Version: 106.0.3 (64-bit)
- I'm using the msix package (Windows Store)
- OS: Windows 11 22h2

**Comment by LordMethenor** [comment] 2022-11-04 21:23
Huh. I think the window controls are CORRECT when it isn't in focused. Not only that, but it seems to reflect the Windows 11 design. 
![image](https://user-images.githubusercontent.com/37001137/200077024-cdf9a5a4-991e-4bdd-b17f-7e10a5b638d7.png)

**Comment by LordMethenor** [comment] 2022-11-04 21:27
![image](https://user-images.githubusercontent.com/37001137/200077405-319e4b82-481c-49ab-90a6-37ae30a2031a.png)
It seems like it renders properly when the window isn't in focus. The style of the maximize button looks more consistent with Windows 11 too.

**Comment by LordMethenor** [comment] 2022-11-04 21:34
Another edit: I tested unplugging the primary display, and it still happened. My laptop screen is 3:2 2256x1504 175% scaling. My primary monitor (on which it works) is 16:9 1920x1080 100% scaling.

**Comment by bmFtZQ** [comment] 2022-12-08 03:36
When using the Mica tweak and the window is focused, the icons are drawn by windows but the button background when you hover over them is drawn by Firefox. The theme hides the window icons because the Mica appearance forces a set of window icons to appear. When the window is inactive the icons are drawn by Firefox, as Mica is disabled and the window background becomes a solid colour.

The misalignment seems to be caused by inconsistent button sizes when using fractional scaling settings. But there isn't any way to get the proper size of the icons. So I think the only way to fix this would be to add different sizes for different scaling settings. But I'll have to work on this another time, as Windows is not the operating system I use.

**Comment by bmFtZQ** [comment] 2023-12-20 03:41
Closing this due to Mica being no longer supported as this issue only occurred with Mica enabled.

**Closed by bmFtZQ** 2023-12-20 03:41 UTC
Labels: bug
