### ISSUE TITLE
Mica and Some Button SVG Files Can't use in Firefox 117 and Up

### ISSUE THREAD

**Issue by StevenChang1892** [bmFtZQ/edge-frfox#101] opened 2023-09-16 17:17 UTC
**Description**
I am experiencing the same issue as reported in the link below where the Mica effect is missing and the minimize, maximize, and close buttons for the window are all the default ones instead of using the svg files.

**Inferred Cause**
I guess it was the new update to change the rules. Maybe it deleted or changed a value `-moz-win-borderless-glass`.

> Reference link: https://github.com/bmFtZQ/edge-frfox/issues/98#issuecomment-1698402407
![Release Note](https://github.com/bmFtZQ/edge-frfox/assets/115457858/9bc55f25-4587-46d4-845c-f9ee55cf24e0)
URL: https://www.mozilla.org/en-US/firefox/117.0/releasenotes/?utm_source=firefox-browser&utm_medium=firefox-desktop&utm_campaign=about-dialog

**Reproduce**
##### Buttons
After installing this theme, you will see that.

##### Mica
See this link: https://github.com/bmFtZQ/edge-frfox#mica-tweak-instructions-windows-11-only

**Include screenshot / video recording if possible.**

##### Buttons
![The Photo of The Buttons](https://github.com/bmFtZQ/edge-frfox/assets/115457858/7a308b37-8bae-4d19-aed9-0f5048f1b5b0)

##### Mica
![Mica Effect](https://github.com/bmFtZQ/edge-frfox/assets/115457858/298d620d-4132-4f81-906b-00974b888a63)
![The Wallpaper](https://github.com/bmFtZQ/edge-frfox/assets/115457858/f2fd5c1b-d1f7-485c-8e4a-717faa10dc72)
![Firefox](https://github.com/bmFtZQ/edge-frfox/assets/115457858/2cd21695-c277-4e75-8ffb-3430f4dd24da)

**Configuration**
- Firefox Version: 117.0.1
- OS: Microsoft Windows 11 22H2 Build 22621.2215

**Comment by StevenChang1892** [comment] 2023-09-16 17:24
Buttons Reference source code: https://github.com/bmFtZQ/edge-frfox/blob/main/chrome/icons/icons.css
```css
@media (-moz-windows-compositor),
(-moz-gtk-csd-available) {
  .titlebar-min {
    list-style-image: url("win11-minimize.svg") !important;
  }

  .titlebar-max {
    list-style-image: url("win11-maximize.svg") !important;
  }

  .titlebar-restore {
    list-style-image: url("win11-restore.svg") !important;
  }

  .titlebar-close {
    list-style-image: url("win11-close.svg") !important;
  }
```
The implementation method of Mica effect is not yet known.

**Comment by StevenChang1892** [comment] 2023-10-16 15:43
No one at here to see them?
Oh c'mon😅

**Comment by bmFtZQ** [comment] 2023-10-25 12:38
The window control button icons should work now. Unfortunately Mica does not work in newer versions of Firefox.

**Comment by bmFtZQ** [comment] 2023-10-26 03:54
Mozilla removed the CSS `appearance` value (`-moz-win-borderless-glass`) that this theme used for Mica. This value was designed to be used for the Aero effect on Windows 7, but when using Mica For Everyone, the same value could be used for the Mica effect. Firefox 116 removed support for Windows 7 and 8, so the `-moz-win-borderless-glass` value was also removed.

**Comment by bmFtZQ** [comment] 2023-11-24 11:59
Mica has been removed from this theme due to the removal of the appearance values. As of now since there is no way to use Mica in newer versions of Firefox, I will be closing this as not planned.

**Closed by bmFtZQ** 2023-11-24 11:59 UTC
Labels: bug

**Comment by StevenChang1892** [comment] 2023-11-24 14:33
👌
