### ISSUE TITLE
Tab bar giggly

### ISSUE THREAD

**Issue by EdwardLangdon** [bmFtZQ/edge-frfox#31] opened 2022-06-10 14:12 UTC
When I click on Customize Toolbar, the whole tab bar is jiggly even if you just hover over one of the extensions and while arranging things.

**Comment by EdwardLangdon** [comment] 2022-06-10 14:13
This happens since the time I started using your CSS not cause by the new Release

**Comment by bmFtZQ** [comment] 2022-06-10 14:32
Can you send a screen recording showing the issue, because I can't seem to replicate it.

https://user-images.githubusercontent.com/62812711/173088039-e5ec771a-db67-44e1-a9a2-eced51cce9df.mov

**Comment by EdwardLangdon** [comment] 2022-06-10 14:37
As you asked, I will do that. But I will do that later as I don't have time to do it now.

A detail, Can you check this in Windows ?

**Comment by bmFtZQ** [comment] 2022-06-10 14:39
> A detail, Can you check this in Windows ?

The same thing happens, it was just easier for me to get a screen recording on macOS.

**Comment by EdwardLangdon** [comment] 2022-06-10 14:52
For a Info, I will try this on a New Profile and record and send it here within this weekend.

**Comment by EdwardLangdon** [comment] 2022-06-11 06:00
For this, I would suggest you to have opened to Customize Toolbar opened for a short amount of time such as 2 Mins or so. Browse something, Come back and you might see the effect but only for a short amount of time and it fixes itself.

**The above happened when I was using a New Profile**. In my Old Profile, Which was totally broken has the effect whenever I went there and almost totally unusable. So, I didn't record it. Sorry for that.

I would suggest you to try the first thing. If it doesn't happen. Just close this issue as it seems to be happening less in the New Profile for me and fix itself shortly. I mean the giggly effect stops.

**Comment by EdwardLangdon** [comment] 2022-06-14 08:58
Any Updates on this ?

**Comment by bmFtZQ** [comment] 2022-06-14 11:07
I tested this just now and I can't reproduce this bug. But maybe with more information I can replicate your setup and see if anything changes.

 - What resolution is your display (1920x1080, 1440x2560, etc.)?
 - Display Scaling (100%, 125%, custom)?
 - Did any specific amount of tabs or toolbar configuration cause this?

**Comment by EdwardLangdon** [comment] 2022-06-14 11:18
- 1366 x 768
- 100%
- I had about 3 including the Customize tab

**Comment by bmFtZQ** [comment] 2022-06-14 12:46
I been able to replicate the issue now in a Windows VM (didn't happen on macOS for some reason). I have two theories why this might be happening:

1. Tab separators
To add tab separators the each tab is moved to the left by 1px this might be able to cause the tabs to overflow and go into scrolling mode, but then the size is recalculated and they go back to normal (this is what creates the flickering effect.)

2. Tab bottom corner radius
The bottom corner radius of the tabs use `::before` and `::after` elements that are positioned out side of the space taken up by the rest of the tab (this might cause the same size miscalculation)

I will have to test which of the two is the culprit, but also: does this only happen in the customisation view? if so these effects can just be disabled when customising the toolbar layout.

**Comment by EdwardLangdon** [comment] 2022-06-14 12:49
Yeah, It happens only when Customizing toolbar layout.

What effects are you talking about ?

**Comment by EdwardLangdon** [comment] 2022-06-14 12:53
While customizing you will disable the effects, That's cool. But, What's Bottom Corner radius ?

**Comment by bmFtZQ** [comment] 2022-06-14 12:57
> What's Bottom Corner radius ?

The rounded part where the tab meets the toolbar:
![Screen Shot 2022-06-14 at 20 54 20](https://user-images.githubusercontent.com/62812711/173582172-71d61785-fb93-45f3-add3-b6ae5b7ba718.png)

**Comment by EdwardLangdon** [comment] 2022-06-14 13:17
Okay, I get it now.

I had a weird issue. When I kept the tab open for a few minutes and come back to it like in this image.

![image](https://user-images.githubusercontent.com/101938856/173586257-af1b2ec3-0332-45cf-85e4-703f5dfc0357.png)

It's fixed When I went to other tabs and comeback. Though it was giggly.

**Comment by EdwardLangdon** [comment] 2022-06-14 13:49
Sure, I will copy and paste from my fork after fetching. But Can you clarify the Updater script more in the Readme ?

Because the script for windows doesn't seem to work.

**Comment by bmFtZQ** [comment] 2022-06-14 14:05
> Can you clarify the Updater script more in the Readme ?
> 
> Because the script for windows doesn't seem to work.

Assuming you're talking about: https://github.com/bmFtZQ/userchrome-update-script

What exact steps have you performed to use the script? Do you get an error message or does it silently fail?

**Comment by EdwardLangdon** [comment] 2022-06-14 14:17
The Main issue is fixed. No Giggly behaviour. But the Tab flicker a little bit. When switching from Customize toolbar tab to another. Just 1 tab flickers not everything. Not a giggly behaviour but like a quick reload but not actually a reload.

> What exact steps have you performed to use the script? Do you get an error message or does it silently fail?

I replaced this line

```
set PROFILEDIR=C:\Users\%USERNAME%\AppData\Roaming\Mozilla\Firefox\Profiles\xxxxxxxx.default-release
```
like in the Profile Dir name in below image.

![image](https://user-images.githubusercontent.com/101938856/173598808-ed387000-4f26-408b-8317-e1588f982a3f.png)

And Also changed my Username in the codeblock. That's what I changed.


The Script opens and closes doesn't seem to update things. Because when I checked the folder for changes. It's still the same time when I last copied the CSS.

**Comment by bmFtZQ** [comment] 2022-06-14 14:48
I think opening an issue in the script repository would be better for this.

But would you be able navigate to the directory the script is located in `cmd` and run: `windows.bat > output.txt`, then verify the `output.txt` file against: https://gist.github.com/bmFtZQ/a2d626bf2bf315a2ada5f0a0a4eae9fa

They should be almost identical (aside from username, firefox profile)

Side note: the `%USERNAME%` part doesn't need to be replaced as that will fetch your username when you run the script.

**Comment by EdwardLangdon** [comment] 2022-06-14 15:13
For the Script, I made a silly mistake. I tried it a new profile which I didn't open while using. After updating, Then I turned the `about:config` toggles in the readme necessary for enabling CSS and restarted firefox, it worked.

Sorry for about that.

What about the minute flicker that appears. If you can fix it, It would be great. The effect is like after switching from customizer to other sites, it sort of acts like resizing on its own.

That's it. If you can fix it. Do and close this. If not, Close this and take a break.

**Comment by bmFtZQ** [comment] 2022-06-14 15:27
> What about the minute flicker that appears. If you can fix it, It would be great. The effect is like after switching from customizer to other sites, it sort of acts like resizing on its own.

I haven't been able to find any flicker so I'll just close this issue, if it gets worse just open a new issue.


> Sorry for about that. I am glad that an updater like this exist for easy use. Maybe you should link it in the readme of this repo.

I'll probably add it in the readme eventually, but probably an other day.

**Closed by bmFtZQ** 2022-06-14 15:27 UTC
