### ISSUE TITLE
PiP broken

### ISSUE THREAD

**Issue by Schoggiweggli** [bmFtZQ/edge-frfox#130] opened 2024-01-29 19:48 UTC
The media controls are missing from the PiP window when Edge-Frfox is installed.
Doubleclick to go full screen from the PiP window doesn't work either, nothing happens.

### Configuration
* Firefox Version: 122.0
* OS: Windows 10 x64
* Tweaks enabled: uc.tweak.rounded-corners

**Comment by KiKaraage** [comment] 2024-01-30 14:18
Experienced similar thing. In my case, media controls still exist for videos, but there's no progress bar at all. Music PiP just showed the close and enlarge button

**Comment by bmFtZQ** [comment] 2024-01-30 14:53
This should be fixed in the latest commit. This was caused by the video element and the browser element in the main window sharing the same ID. A rule that changes the z-index of the browser was used to prevent overlapping toolbars when the rounded corners tweak was enabled.

The controls were still being displayed, but they were behind the video player. This should be fixed in the newest commit of the theme.

**Closed by bmFtZQ** 2024-01-30 14:53 UTC
Labels: bug
