### ISSUE TITLE
Mica theme color doesn't switch correctly after changing the Windows app theme while the browser is closed

### ISSUE THREAD

**Issue by CherryQuartzio** [bmFtZQ/edge-frfox#54] opened 2022-07-22 04:04 UTC
After switching the Windows app theme between light and dark mode while Firefox is closed, opening the first browser window will result in the mica effect retaining the color of the previous theme (Example: Mica still shows light theme even though the browser already switched to dark theme and vice versa). The workarounds are to either open the browser window the second time (the first opened window still retain the problem) or leave the browser open when switching theme. The issue is only visible when the first browser window is in focus and only applies to non-private window.

![Light to dark](https://user-images.githubusercontent.com/85609395/180359309-951aabd7-0844-4083-882f-8eff2ad69519.png)
First window after switching from light to dark

![Dark to light](https://user-images.githubusercontent.com/85609395/180359352-fcb66e20-9ae9-407a-ab05-788a4f9a8c2d.png)
First window after switching from dark to light

**Comment by bmFtZQ** [comment] 2022-07-26 15:18
This is something caused by Firefox not selecting the right theme for some reason when starting the browser. Unfortunately there isn't anything that I know of that can fix this.

**Comment by bmFtZQ** [comment] 2023-12-20 03:40
Closing this due to Mica being no longer supported.

**Closed by bmFtZQ** 2023-12-20 03:40 UTC
