### ISSUE TITLE
Horizontal scrolling glitch

### ISSUE THREAD

**Issue by Trident6355** [bmFtZQ/edge-frfox#45] opened 2022-06-26 11:20 UTC
![img](https://user-images.githubusercontent.com/105816068/175811349-e58aca84-38cc-4b0b-b110-178eb4f36100.png)
For some reason, the horizontal scrolling on this theme kicks in too early. 
On default Firefox, horizontal scrolling starts at ~20 open tabs.
On this theme, it already begins way too early at just 7 tabs. There is nothing to scroll anyway, so it takes up unnecessary space.
Also, it seems like the "New Tab" animations disappear when this horizontal scrolling glitch occurs. There are no animations at all.
For example, this is how it should look like, on default Firefox:
![img 2](https://user-images.githubusercontent.com/105816068/175811549-58e95716-b439-4192-912d-4f4624326b2f.png)

**Comment by EdwardLangdon** [comment] 2022-06-26 11:23
Also, The Close button hides too soon. Which is uneasy. Whereas firefox shows the close button No matter what. It would be better to support it.

**Comment by bmFtZQ** [comment] 2022-07-14 13:53
Does this issue still happen now? The tabs were a little bit glitchy on Firefox 101, but it seems that upgrading to Firefox 102 fixed some issues.

**Comment by EdwardLangdon** [comment] 2022-07-14 13:54
Will check now.

**Comment by bmFtZQ** [comment] 2022-07-14 13:55
> Also, The Close button hides too soon. Which is uneasy. Whereas firefox shows the close button No matter what. It would be better to support it.

Are `browser.tabs.tabMinWidth` and `browser.tabs.tabClipWidth` both set to `66`. The close button and tab overflow behaviour seems to be dependant on those settings.

**Comment by EdwardLangdon** [comment] 2022-07-14 14:13
The thing with this config, I can see the close button on every tabs but I can't see after 16 tabs are opened. But the tab overflow button which OP mentions about coming at 7 tabs comes at 16 tabs.

This is before using the latest commit.

**Comment by bmFtZQ** [comment] 2022-07-14 14:28
> The thing with this config, I can see the close button on every tabs but I can't see after 16 tabs are opened. But the tab overflow button which OP mentions about coming at 7 tabs comes at 16 tabs.

Firefox will hide the close button when the width of the tabs is less than `browser.tabs.tabClipWidth` (default: 140) or when the tabs overflow. The tabs will overflow when the width of the tab is the value of `browser.tabs.tabMinWidth` (default: 76) or less.

The close buttons disappearing on inactive tabs when overflowed is expected behaviour by default.

**Comment by EdwardLangdon** [comment] 2022-07-14 14:32
But the thing is after and before your commit, Overflow menu appears after 16 tabs which is better than OP stated.

Now, the Problem is I don't see close buttons on inactive/not using tabs when hovering over that tab.

**Comment by bmFtZQ** [comment] 2022-07-14 14:52
> Now, the Problem is I don't see close buttons on inactive/not using tabs when hovering over that tab.

That is expected behaviour by default. If the tabs are overflowed, the close buttons will be hidden on inactive tabs. I will be making a tweak to always show the close button.

**Comment by EdwardLangdon** [comment] 2022-07-14 15:18
But why not show on the specific tab alone when hover instead showing the button on every tab every time ?

**Comment by EdwardLangdon** [comment] 2022-07-15 01:18
That's it. Then. You could close this issue probably.

**Comment by Trident6355** [comment] 2022-07-17 20:37
Yes, my issue is fixed now. Thanks a lot for your hard work Sir! Really appreciate your effort, this is probably the best and most polished Firefox theme right now.

**Closed** 2022-07-17 20:38 UTC
